Fix to provide the valid input for the message size.
CDCgov/NEDSS-DataIngestion-CLI pull request #16
Opened 2024-01-24 19:39 UTC by ssathiah

Fix to provide the valid input for the message size.
If the user enters an invalid input like non-numeric and negative numbers, the command returns the message "Invalid input. Please enter a positive number."

https://cdc-nbs.atlassian.net/browse/CNDIT-914

2024-01-24 19:48 UTC, rshanmugam-enquizit requested changes

2024-01-24 19:48 UTC, rshanmugam-enquizit commented on src/main/java/gov/cdc/dataingestion/commands/DeadLetterMessages.java
Also, can you change `--msgsize` argument to `--msg-size` just to be consistent with all other commands?

2024-01-24 23:08 UTC, ssathiah commented on src/main/java/gov/cdc/dataingestion/commands/DeadLetterMessages.java
Changed --msgsize argument to --msg-size

2024-01-25 17:27 UTC, ssathiah commented on src/test/java/gov/cdc/dataingestion/commands/DeadLetterMessagesTest.java
> +        String expectedOutput = expOutput;
Done.

2024-01-25 17:28 UTC, merged